name: todo_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  #architecture
  flutter_bloc: ^8.0.1
  flutter_form_bloc: ^0.30.1
  get_it: ^7.0.0
  injectable: ^1.5.0

  #storage
  hive: 2.0.6
  hive_flutter: ^1.1.0
  
  #ui
  cupertino_icons: ^1.0.0
  flutter_i18n: ^0.32.0

  # network
  http: ^0.13.4
  dio: ^4.0.4

  intl: ^0.17.0
  logger: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.1.7
  freezed: ^2.0.3+1
  hive_generator: ^1.1.0
  injectable_generator: ^1.2.0
  flutter_launcher_icons: ^0.9.1

  flutter_native_splash: 2.1.6

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png

flutter_icons:
  ios: true
  remove_alpha_ios: true
  android: true
  image_path_ios: "assets/icons/icon.png"
  image_path_android: "assets/icons/icon.png"


flutter:
  uses-material-design: true
  
  
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
    